# Generated by Django 4.2.6 on 2023-10-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Esame",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=255)),
                ("esito", models.CharField(max_length=255)),
                ("struttura", models.CharField(default="prova", max_length=255)),
                ("file_referto", models.FileField(upload_to="")),
                ("cda2", models.TextField()),
            ],
        ),
    ]
