# Generated by Django 4.2.6 on 2023-10-27 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("gestionale", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="esame",
            name="data_ora",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
