# Generated by Django 4.2.7 on 2023-11-07 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gestionale", "0002_esame_data_ora"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paziente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice_fiscale", models.CharField(max_length=16)),
                ("nome", models.CharField(max_length=255)),
                ("cognome", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="esame",
            name="paziente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestionale.paziente",
            ),
        ),
    ]
